version: '3'
services:
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker_1
    volumes:
      - /app/node_modules
      - ./worker:/app
    command: nodemon app.js -L
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8081:8081"
    volumes:
      - /app/node_modules
      - ./server:/app
    command: node app.js
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - /app/node_modules
      - ./front:/app
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run serve