version: "3"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - /app/node_modules
      - ./front:/app
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run build
